### PR TITLE
Add DevCode dark theme

### PR DESCRIPTION
**Pull request by Mokudjinn**
Hi, I made this dark theme in Godot 4.3.
It's a bit less contrasted than my usual color theme, but perfectly fits my needs in Godot.
Hope you like it !

### CODE REVIEW

**Comment by Mokudjinn** [comment]
DevCode_preview

**Review by Calinou — APPROVED** [review]
Thanks!

**Comment by Mokudjinn** [comment]
Thank you @Calinou 
Do I have to also modify the Themes.md code to add the preview of my theme or you can do it ?

**Comment by Mokudjinn** [comment]
Ok, sounds good.
Thank you.

**Pull request merged**
